#!/usr/bin/env python
import sys

try:
    from luna_ansible.inventory import LunaInventory
except:
    print({"_meta": {"hostvars": {}}})
    sys.exit(0)


if __name__ == '__main__':
    LunaInventory()
